WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER=FREEPDB1;
CREATE USER tui_proxy IDENTIFIED BY "&1";
GRANT CREATE SESSION TO tui_proxy;
ALTER USER tui_test GRANT CONNECT THROUGH tui_proxy;
EXIT;
